export const STEPPER_SET = "STEPPER/SET"
export const STEPPER_SET_LOADING = "STEPPER/SET_LOADING"
export const STEPPER_SET_FAILURE = "STEPPER/SET_FAILURE"
export const STEPPER_RESET = "STEPPER/RESETT_JOBS"
