export const ORDER_SET = "STEPPER/SET"
export const ORDER_SET_LOADING = "STEPPER/SET_LOADING"
export const ORDER_SET_FAILURE = "STEPPER/SET_FAILURE"
export const ORDER_RESET = "STEPPER/RESETT_JOBS"
// items
export const ORDER_SET_ITEMS = "STEPPER/SET_ITEMS"
export const ORDER_SET_ITEMS_LOADING = "STEPPER/SET_ITEMS_LOADING"
